### ISSUE TITLE
Discussion about choosing the right database

### ISSUE THREAD

**Issue by majia67** [sarahhh000/real-time-big-data#5]
这个issue里面，我们讨论一下用哪种database比较合适：HBase, Hive, 还是impala？

**Comment by sarahhh000** [comment]
We do not need to use the same database. Each of us could decide their own database choice.

**Comment by majia67** [comment]
我建议还是用同一个database，因为之后需要整合feature，用同一个database会比较方便

**Comment by sarahhh000** [comment]
All data could be merged together into any database. It's not hard to do. But if you insist, I vote for Impala.

**Comment by PokerMao** [comment]
Here's a rather detailed comparison between impala and hive. Since we're not dealing with huge data size and may want low latency response, impala suits the program better. 
Detailed comparison: https://www.dezyre.com/article/impala-vs-hive-difference-between-sql-on-hadoop-components/180
Concise comparison: https://www.dezyre.com/article/hive-vs-impala-sql-war-in-the-hadoop-ecosystem/148

**Comment by majia67** [comment]
Impala is more suitable for this project. Let's conclude with using Impala. Thanks for the great discussion on this!
